main: ca.evannosich.slabtoblocks.SlabToBlocks
name: SlabToBlocks
api-version: 1.13
version: 0.2
author: Evan Nosich (ComradeBushtail)
description: A plugin that allows players to combine 2 slabs in a crafting table to create a full block.
