main: ca.evannosich.SlabToBlocks.SlabToBlocks
name: SlabToBlocks
api-version: 1.14
version: 1.3
author: Evan Nosich (ComradeBushtail)
description: A plugin that allows players to combine 2 slabs in a crafting table to create a full block.
